name: jfrogcli
description: Jfrogcli
inputs:
  version:
    description: "JFrog CLI Version"
    default: "1.46.4"
    required: false
  build-name:
    description: "build name"
    required: false
  build-number:
    description: "Build Number"
    required: false
  build-type:
    description: "action to be taken"
    required: true
  resolve-server-id:
    description: "action to be taken"
    required: false
  deploy-server-id:
    description: "action to be taken"
    required: false
  resolve-snapshot-repository:
    description: "action to be taken"
    required: false
  deploy-snapshot-repository:
    description: "action to be taken"
    required: false
  resolve-releases-repository:
    description: "action to be taken"
    required: false
  deploy-releases-repository:
    description: "action to be taken"
    required: false
  jfrog-project:
    description: "action to be taken"
    required: false
  build-fail-onscan:
    description: "action to be taken"
    required: false

runs:
  using: "node12"
  main: "dist/index.js"
